### ISSUE TITLE
Cenit server having boot issues on local

### ISSUE THREAD

**Issue by emanulz** [cenit-io/cenit#3006]
Hi team, 

We are exploring options to build a new product and use cenit as a base to work on top of it.

Following the docs I tried to install cenit on local and found a couple of issues:
https://docs.cenit.io/docs/installation/alternative

- The docs stated that ruby 2.5.5 is needed, but the rails app needs 2.7.4
- After installing all the gems with right ruby version I am having the following boot errors:

```
Redis connection detected!
Clearing LOCKS
DELETING CANCELLED Consumers
Creating build-in apps
Couldn't create build-in app Cenit::OauthApp: Mongoid. Errors. Validations: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.
Couldn't create build-in app Cenit::OpenId: Mongoid. Errors. Validations: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.
Couldn't create build-in app Cenit::Admin: Mongoid. Errors. Validations: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.
Couldn't create build-in app Cenit::MIME: Mongoid. Errors. Validations: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.: 
message:
  Validation of Account failed.
summary:
  The following errors were found: Token is already taken
resolution:
  Try persisting the document with valid data or remove the validations.
RABBIT CONSUMER 'cenit_dev'-1671057386000-269755376207' STARTED
Lookup scheduler STARTED
Redis Hook adapter subscribed to #hook (1 subscriptions)
2022-12-14 16:36:26 -0600 Thin web server (v1.8.1 codename Infinite Smoothie)
2022-12-14 16:36:26 -0600 Maximum connections set to 1024
2022-12-14 16:36:26 -0600 Listening on localhost:3000, CTRL+C to stop
Started GET "/" for ::1 at 2022-12-14 16:37:14 -0600
Processing by ApplicationController#index as HTML
Completed 500 Internal Server Error in 5ms (MongoDB: 0.0ms | Allocations: 669)
```

- And When I try to access localhost:3000
  
```
Mongoid::Errors::InvalidFind (
message:
  Calling Document.find with nil is invalid.
summary:
  Document.find expects the parameters to be 1 or more ids, and will return a single document if 1 id is provided, otherwise an array of documents if multiple ids are provided.
resolution:
  Most likely this is caused by passing parameters directly through to the find, and the parameter either is not present or the key from which it is accessed is incorrect.):
  
app/controllers/application_controller.rb:23:in `block (2 levels) in index'
app/controllers/application_controller.rb:22:in `map'
app/controllers/application_controller.rb:22:in `block in index'
app/models/user.rb:272:in `with_super_access'
app/controllers/application_controller.rb:19:in `index'
app/controllers/application_controller.rb:63:in `scope_current_account'
```
![Screenshot 2022-12-14 at 16 45 25](https://user-images.githubusercontent.com/11077200/207731348-f35d8678-5cd3-4f55-a0c6-1bd690e7c593.png)

- I am on **master** branch and faced the same issue using docker-compose for running the app.

Can someone help me out to see what I'm missing?

Thanks in advance!

**Comment by emanulz** [comment]
Hi team,

Is anyone actively looking at Github issues? Or can anyone point me out the right place to get support? I tried to join the slack channel as stated in the site, but the link is no longer active:

![Screenshot 2022-12-19 at 08 11 10](https://user-images.githubusercontent.com/11077200/208444783-ad090e27-7c4b-4a5f-95b8-f5e02e76ab1e.png)

Also tried to contact by email but no answer so far.

Thanks in advance
